[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2.14"
clap = { version = "4.4.16", features = ["derive", "cargo"] }
clap-verbosity-flag = "2.1.1"
log = "0.4.20"
simple_logger = "4.3.3"
